spring.application.name=resume-matcher
spring.datasource.url=jdbc:postgresql://localhost:5432/resumematcher
spring.datasource.username=postgres
spring.datasource.password=PriyanshuGoldi1437@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ChangeThisToALongRandomSecretKeyForJwtSigning123456
jwt.expiration-ms=86400000